services:
  order-service-app:
    build:
      context: ./
    ports:
      - "8080:8080"
#    env_file:
#      - ./env/web.env
    environment:
      POSTGRES_JDBC_USER: "admin"
      POSTGRES_JDBC_PASSWORD: "admin"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/order-service-db"
    depends_on:
      - order-service-db

  order-service-db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
#    env_file:
#      - ./env/postgres.env
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "order-service-db"
volumes:
  postgres:
